import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";

export default function CatalogReviewDialog({ open, onOpenChange, incompleteProducts, priceReviews, onEditProduct, onOpenReview }) {
  const accessAlerts = priceReviews.filter(review => review.availability === "OutOfStock" || review.availability?.startsWith("Web access") || review.availability === "Price unavailable");
  const priceAlerts = priceReviews.filter(review => !accessAlerts.includes(review));
  const Section = ({ title, items, empty, children }) => <section><div className="mb-2 flex items-center justify-between"><h3 className="font-semibold">{title}</h3><Badge variant="secondary">{items.length}</Badge></div>{items.length ? <div className="max-h-48 space-y-2 overflow-y-auto">{children}</div> : <p className="rounded-lg bg-slate-50 p-3 text-sm text-slate-500">{empty}</p>}</section>;
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-xl"><DialogHeader><DialogTitle>Catalog review</DialogTitle><DialogDescription>Review incomplete listings, retailer price differences, and product web availability alerts.</DialogDescription></DialogHeader><div className="space-y-5"><Section title="Incomplete listings" items={incompleteProducts} empty="All catalog items have a product link.">{incompleteProducts.map(product => <div key={product.id} className="flex items-center justify-between gap-3 rounded-lg border p-3"><span className="text-sm font-medium">{product.name}</span><Button size="sm" variant="outline" onClick={() => onEditProduct(product)}>Complete listing</Button></div>)}</Section><Section title="Price differences" items={priceAlerts} empty="No pricing differences are waiting for review.">{priceAlerts.map(review => <div key={review.id} className="flex items-center justify-between gap-3 rounded-lg border p-3"><span className="text-sm font-medium">{review.product_name}</span><Button size="sm" variant="outline" onClick={() => onOpenReview(review)}>Review</Button></div>)}</Section><Section title="Stock & web access" items={accessAlerts} empty="No stock or web access alerts are waiting for review.">{accessAlerts.map(review => <div key={review.id} className="flex items-center justify-between gap-3 rounded-lg border p-3"><div><p className="text-sm font-medium">{review.product_name}</p><p className="text-xs text-slate-500">{review.availability}</p></div><Button size="sm" variant="outline" onClick={() => onOpenReview(review)}>Review</Button></div>)}</Section></div></DialogContent></Dialog>;
}