$ErrorActionPreference = "Stop"

Write-Host "=== Setting up a SAFE local copy of your production Base44 data ==="
Write-Host ""
Write-Host "This creates a read-only snapshot of your real quotes/products and"
Write-Host "wires your app to use that LOCAL copy for testing -- your app will"
Write-Host "have ZERO network connection to Base44 while VITE_DATA_SOURCE=mock"
Write-Host "is active. Nothing you do in the app while testing can affect your"
Write-Host "real production quote data."
Write-Host ""

# -------------------------------------------------------------------------
# STEP 1: Write the read-only export script
# -------------------------------------------------------------------------
Write-Host "Step 1: Writing export-production-data.mjs (read-only)..."

@'
// export-production-data.mjs
//
// READ-ONLY export script. Connects to your REAL production Base44 app
// using the credentials you provide as environment variables, and ONLY
// calls .list() on entities -- it never calls .create(), .update(),
// .delete(), or any write method. This script cannot modify production
// data in any way.
//
// It writes a local snapshot of your Quotes and Products into
// src/mockData/quotes.export.js and src/mockData/products.export.js.
// Nothing is overwritten automatically -- you review and rename these
// files yourself in Step 2 below, so you always know exactly what data
// your app is using.
//
// Run this with: node export-production-data.mjs
// (from your EnQuote project root, after `npm install @base44/sdk` if you
// haven't already)

import { createClient } from "@base44/sdk";
import { writeFileSync, mkdirSync, existsSync } from "fs";
import path from "path";

// IMPORTANT: This script reads credentials from environment variables --
// never hard-code them here. After you finish this export, rotate the API
// key in your Base44 dashboard, since it was shared outside a secrets
// manager. Store the NEW key only in .env.local (which must be in
// .gitignore), never in a script file that could be committed or shared.
const BASE44_APP_ID = process.env.BASE44_EXPORT_APP_ID || "";
const BASE44_API_KEY = process.env.BASE44_EXPORT_API_KEY || "";

if (!BASE44_APP_ID || !BASE44_API_KEY) {
  console.error(
    "Missing credentials. Set BASE44_EXPORT_APP_ID and BASE44_EXPORT_API_KEY\n" +
    "as environment variables before running this script, e.g.:\n\n" +
    '  $env:BASE44_EXPORT_APP_ID = "your-app-id"\n' +
    '  $env:BASE44_EXPORT_API_KEY = "your-api-key"\n' +
    "  node export-production-data.mjs\n"
  );
  process.exit(1);
}

const base44 = createClient({
  appId: BASE44_APP_ID,
  headers: {
    api_key: BASE44_API_KEY
  }
});

const OUTPUT_DIR = path.resolve("./src/mockData");

function toJsModule(varName, data) {
  return `// Auto-generated by export-production-data.mjs on ${new Date().toISOString()}\n` +
    `// This is a READ-ONLY snapshot of production data for local testing.\n` +
    `// Regenerate by re-running the export script -- do not hand-edit for long-term use.\n\n` +
    `export const ${varName} = ${JSON.stringify(data, null, 2)};\n`;
}

async function main() {
  console.log("Connecting to Base44 (read-only export)...");

  if (!existsSync(OUTPUT_DIR)) {
    mkdirSync(OUTPUT_DIR, { recursive: true });
  }

  console.log("Fetching quotes (read-only .list() call)...");
  let quotes = [];
  try {
    quotes = await base44.entities.Quote.list("-created_date", 500);
    console.log(`  Retrieved ${quotes.length} quote(s).`);
  } catch (err) {
    console.error("  Failed to fetch quotes:", err.message);
  }

  const quotesPath = path.join(OUTPUT_DIR, "quotes.export.js");
  writeFileSync(quotesPath, toJsModule("mockQuotes", quotes), "utf8");
  console.log(`  Wrote: ${quotesPath}`);

  console.log("Fetching products (read-only call)...");
  let products = [];
  try {
    const response = await base44.functions.invoke("getAllProducts", {});
    products = response?.data?.products || [];
    console.log(`  Retrieved ${products.length} product(s).`);
  } catch (err) {
    console.error("  Failed to fetch products (OK if your app doesn't use this function):", err.message);
  }

  const productsPath = path.join(OUTPUT_DIR, "products.export.js");
  writeFileSync(productsPath, toJsModule("mockProducts", products), "utf8");
  console.log(`  Wrote: ${productsPath}`);

  console.log("");
  console.log("Done. Files written to src/mockData/quotes.export.js and products.export.js");
  console.log("Follow Step 2 printed below to activate them for local testing.");
}

main().catch((err) => {
  console.error("Export failed:", err);
  process.exit(1);
});
'@ | Set-Content -Encoding utf8 .\export-production-data.mjs

Write-Host "  Wrote: export-production-data.mjs"
Write-Host ""
Write-Host "=== NEXT STEPS (manual -- these are NOT run automatically) ==="
Write-Host ""
Write-Host "1. Install the SDK if you have not already:"
Write-Host "     npm.cmd install @base44/sdk"
Write-Host ""
Write-Host "2. Set your credentials as TEMPORARY environment variables"
Write-Host "   (this keeps them out of any script file on disk):"
Write-Host '     $env:BASE44_EXPORT_APP_ID = "6979390a3f44099ffca06859"'
Write-Host '     $env:BASE44_EXPORT_API_KEY = "<paste your API key here>"'
Write-Host ""
Write-Host "3. Run the read-only export:"
Write-Host "     node export-production-data.mjs"
Write-Host ""
Write-Host "4. Review the two files it created:"
Write-Host "     src\mockData\quotes.export.js"
Write-Host "     src\mockData\products.export.js"
Write-Host "   Confirm this looks like real quote/product data before proceeding."
Write-Host ""
Write-Host "5. Back up your existing mock files, then activate the real snapshot:"
Write-Host "     Copy-Item .\src\mockData\quotes.js .\src\mockData\quotes.backup.js -ErrorAction SilentlyContinue"
Write-Host "     Copy-Item .\src\mockData\products.js .\src\mockData\products.backup.js -ErrorAction SilentlyContinue"
Write-Host "     Copy-Item .\src\mockData\quotes.export.js .\src\mockData\quotes.js -Force"
Write-Host "     Copy-Item .\src\mockData\products.export.js .\src\mockData\products.js -Force"
Write-Host ""
Write-Host "6. Switch your app to mock mode (zero Base44 connectivity while testing):"
Write-Host "     (Get-Content .env.local) -replace '^VITE_DATA_SOURCE=.*', 'VITE_DATA_SOURCE=mock' | Set-Content .env.local"
Write-Host ""
Write-Host "7. Restart your dev server:"
Write-Host "     npm.cmd run dev"
Write-Host ""
Write-Host "8. IMPORTANT -- clear the credentials from this terminal session:"
Write-Host '     Remove-Item Env:\BASE44_EXPORT_APP_ID'
Write-Host '     Remove-Item Env:\BASE44_EXPORT_API_KEY'
Write-Host ""
Write-Host "9. IMPORTANT -- rotate/regenerate the API key in your Base44 dashboard"
Write-Host "   now that it has been used and shared outside a secrets manager."
Write-Host "   Store any NEW key only in .env.local (gitignored), never in chat"
Write-Host "   or in a committed file."
Write-Host ""
Write-Host "When you are done testing and want to reconnect to real Base44 data,"
Write-Host "switch VITE_DATA_SOURCE back to 'base44' in .env.local and restart"
Write-Host "your dev server."
