export const PRODUCT_CATALOG = [
  { name: "60 Amp Brass 1-Time Fuse Cartridges (2-Pack)", category: "Breakers", unit_price: 8.55, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "FRN Series 40 Amp Brass Time-Delay Cartridge Fuses (2-Pack)", category: "Breakers", unit_price: 27.97, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "Square D HOM215 Homeline 15A 2-Pole 120/240V Circuit Breaker", category: "Breakers", unit_price: 18.24, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "BR 60 Amp 120/240 Volts 2-Pole Circuit Breaker", category: "Breakers", unit_price: 21.32, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "BR 40 Amp 120/240 Volts 2-Pole Circuit Breaker", category: "Breakers", unit_price: 21.32, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "BR 20 Amp 120/240 Volts 2-Pole Circuit Breaker", category: "Breakers", unit_price: 21.32, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "BR 50 Amp 120/240 Volts 2-Pole Circuit Breaker", category: "Breakers", unit_price: 21.32, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "BR 80 Amp 120/240 Volts 2-Pole Circuit Breaker", category: "Breakers", unit_price: 55.19, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "20Amp Eaton BR120", category: "Breakers", unit_price: 8.21, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "QD Sealing Cap (female) - 10 pack", category: "Conduit & Raceway", unit_price: 40.5, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "Field Wireable QD Connector (female) - 10 pack (Commercial)", category: "Conduit & Raceway", unit_price: 135.0, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "Field Wireable QD Connector (male) - 10 pack (Commercial)", category: "Conduit & Raceway", unit_price: 135.0, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "Enphase Field Wireable QD Connector (male) 1 pack (Commercial) (Engage Splice)", category: "Conduit & Raceway", unit_price: 13.5, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "Field Wireable QD Connector (female) 1 pack (Commercial) (Engage Splice)", category: "Conduit & Raceway", unit_price: 13.5, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "Halex 1/2 in. Liquid-Tight Connector", category: "Conduit & Raceway", unit_price: 7.25, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "Solar Panel Bird Wire 6 in. x 98 ft. Critter Guard Roll Kit Removable Steel Solar Panel Guard with Fasteners", category: "Critter Guard", unit_price: 41.75, unit: "each", tax_category: "SOLAR_ACCESSORY", tax_code: "TTR146718" },
  { name: "Critter Guard Fastener Clips 120Pcs Set", category: "Critter Guard", unit_price: 40.0, unit: "each", tax_category: "SOLAR_ACCESSORY", tax_code: "TTR146718" },
  { name: "Critter Guard Roll Kit 8 in. x 98 ft. Clips included", category: "Critter Guard", unit_price: 59.62, unit: "roll", tax_category: "SOLAR_ACCESSORY", tax_code: "TTR146718" },
  { name: "Critter Guard Roll Kit 6 in. x 98 ft. Clips included", category: "Critter Guard", unit_price: 44.17, unit: "roll", tax_category: "SOLAR_ACCESSORY", tax_code: "TTR146718" },
  { name: "11 inch Black UV-Rated Zip Ties", category: "Critter Guard", unit_price: 9.48, unit: "each", tax_category: "SOLAR_ACCESSORY", tax_code: "TTR146718" },
  { name: "Mid-Clamps - pack of 20 (approx. cost)", category: "Critter Guard", unit_price: 20.0, unit: "each", tax_category: "SOLAR_ACCESSORY", tax_code: "TTR146718" },
  { name: "Fastener Clips (50 Pack)", category: "Critter Guard", unit_price: 15.0, unit: "each", tax_category: "SOLAR_ACCESSORY", tax_code: "TTR146718" },
  { name: "BR 125 Amp 8-Space 16-Circuit Outdoor Main Lug Loadcenter with Cover", category: "Enclosure", unit_price: 74.45, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "60 Amp 120/240-Volt Fused Safety Switch", category: "Enclosure", unit_price: 221.46, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "60A Outdoor Rated Fused Disconnect", category: "Enclosure", unit_price: 33.65, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "QD Cable Terminator (10 Pack)", category: "Enphase Products", unit_price: 183.0, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "Engage Replacement Cable Adapter - Single Landscape Drop 1.7m (ETD With Field connectors Included)", category: "Enphase Products", unit_price: 47.3, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "Engage Replacement Cable Adapter - Single Portrait Drop 1m (ETD With Field connectors Included)", category: "Enphase Products", unit_price: 41.8, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "Engage Replacement Cable Adapter - Single (ETD With Field connectors Included)", category: "Enphase Products", unit_price: 290.0, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "Consumption Clamp Current Transformer (CT-200-CLAMP)", category: "Enphase Products", unit_price: 34.0, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "IQ Battery 3 Cover & Mounting Bracket", category: "Enphase Products", unit_price: 156.0, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "IQ Combiner 5 HDK", category: "Enphase Products", unit_price: 733.5, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "Replacement IQ Gateway PCB for IQ Combiner 4", category: "Enphase Products", unit_price: 419.5, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "PCT - Production Current Transformer (Meter)", category: "Enphase Products", unit_price: 30.84, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "IQ Field Wireable (socket) Ea. SKU: Q-CONN-10F", category: "Enphase Products", unit_price: 12.9, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "IQ Field Wireable (plug) Ea. SKU: Q-CONN-10M", category: "Enphase Products", unit_price: 12.9, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "IQ Battery 3 (R1)", category: "Enphase Products", unit_price: 1499.0, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "Enphase Control Cable 1 Foot", category: "Enphase Products", unit_price: 1.35, unit: "ft", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "CCT - Consumption Current Transformer (Meter)", category: "Enphase Products", unit_price: 56.54, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "IQ Cable (Q-12-RAW-300)", category: "Enphase Products", unit_price: 1.43, unit: "ft", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "IQ Field Wireable (socket) 10 pack SKU: Q-CONN-10F", category: "Enphase Products", unit_price: 129.0, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "IQ Field Wireable (plug) 10 pack SKU:Q-CONN-10M", category: "Enphase Products", unit_price: 129.0, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "IQ Load Controller", category: "Enphase Products", unit_price: 431.0, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "Enphase Connector Clip (pack of 12)", category: "Enphase Products", unit_price: 36.0, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "Engage Cable Clips (pack of 100)", category: "Enphase Products", unit_price: 44.0, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "IQ Terminator Cap - Single cap", category: "Enphase Products", unit_price: 18.3, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "IQ7PD-72 Microinverter", category: "Enphase Products", unit_price: 79.0, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "Mobile Connect CELLMODEM-07", category: "Enphase Products", unit_price: 499.0, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "IQ Cable Single Drop (portrait)", category: "Enphase Products", unit_price: 18.0, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "IQ Relay Kit", category: "Enphase Products", unit_price: 471.5, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "IQ Sealing Cap (Q-SEAL-10) (10pk)", category: "Enphase Products", unit_price: 33.5, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "IQ Field Wireable (socket/female) (single)", category: "Enphase Products", unit_price: 12.9, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "IQ Field Wireable (plug/male) (single)", category: "Enphase Products", unit_price: 12.9, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "Termination Cap (Q-TERM-10)", category: "Enphase Products", unit_price: 183.0, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "IQ Field Wireable (socket/female) 10-pack (Q-CONN-10F)", category: "Enphase Products", unit_price: 129.0, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "IQ Field Wireable (plug/male) 10-pack (Q-CONN-10M)", category: "Enphase Products", unit_price: 129.0, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "IQ-Cable per foot", category: "Enphase Products", unit_price: 1.46, unit: "ft", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "Enphase Q Cable Landscape (Q-12-17-240)", category: "Enphase Products", unit_price: 654.5, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "Enphase IQ Battery 5P", category: "Enphase Products", unit_price: 3640.25, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "Enphase Envoy Gateway", category: "Enphase Products", unit_price: 485.0, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "Enphase IQ Battery 10T", category: "Enphase Products", unit_price: 5097.0, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "Enphase IQ8+ Microinverter", category: "Enphase Products", unit_price: 171.0, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "Enphase IQ8M Microinverter", category: "Enphase Products", unit_price: 214.99, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "Enphase IQ8 Microinverter (60-cell)", category: "Enphase Products", unit_price: 177.14, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "Enphase DC Adapter Cable (EN4 to MC4)", category: "Enphase Products", unit_price: 93.15, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "Enphase Q Terminator Cap", category: "Enphase Products", unit_price: 5.5, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "Portrait IQ Cable Single drop (Q-12-10-240)", category: "Enphase Products", unit_price: 18.0, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "Enphase Consumption Current Transformers", category: "Enphase Products", unit_price: 51.4, unit: "pair", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "Enphase IQ EV Charger 2 (9.6 kW)", category: "Enphase Products", unit_price: 999.0, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "Enphase IQ Portable Panel", category: "Enphase Products", unit_price: 369.0, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "Enphase IQ PowerPack 1500", category: "Enphase Products", unit_price: 999.0, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "Landscape IQ Cable Single Drop (Q-12-17-240)", category: "Enphase Products", unit_price: 21.0, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "Enphase IQ EV Charger 2 (11.5 kW)", category: "Enphase Products", unit_price: 1124.0, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "Enphase Control Cable", category: "Enphase Products", unit_price: 2.79, unit: "foot", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "Enphase Solar Extension Cables (10m)", category: "Enphase Products", unit_price: 95.0, unit: "set", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "Enphase IQ Combiner 6C", category: "Enphase Products", unit_price: 1754.0, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "Eaton 30 Amp Non-Fusible Safety Switch (DG221URB)", category: "Junction Box", unit_price: 108.61, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "Soladeck-Type Roof Junction Boxes", category: "Junction Box", unit_price: 42.14, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "Cantex 6 in. x 6 in. x 4 in. Junction Box", category: "Junction Box", unit_price: 20.9, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "Liquid Tight Cord Grip (oval gland)", category: "Junction Box", unit_price: 2.11, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "4 in. x 4 in. x 2 in. Junction Box", category: "Junction Box", unit_price: 12.98, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "PVC Junction Box - 5 x 5 x 2 in", category: "Junction Box", unit_price: 17.2, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "6 in. x 6 in. x 4 in. Gray Electrical PVC Junction Box", category: "Junction Box", unit_price: 25.72, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "4 in. 30.3 CU. in. metallic square box", category: "Junction Box", unit_price: 3.98, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "PVC Junction Box (8x8x4)", category: "Junction Box", unit_price: 18.75, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "4x4 Metal Junction Box", category: "Junction Box", unit_price: 3.5, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "NEMA 3R Metal Enclosure (12x10x6)", category: "Junction Box", unit_price: 65.0, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "Cable Entry Gland (PG16)", category: "Junction Box", unit_price: 2.85, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "4x4 Metal Box Cover (Blank)", category: "Junction Box", unit_price: 0.95, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "PVC Junction Box (6x6x4)", category: "Junction Box", unit_price: 12.5, unit: "each", tax_category: "GENERAL_ELECTRICAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "Q.PEAK DUO BLK", category: "Microinverters", unit_price: 286.05, unit: "each", tax_category: "MICROINVERTER", tax_code: "TTR146714" },
  { name: "Enphase IQ8M Microinverter", category: "Microinverters", unit_price: 218.21, unit: "each", tax_category: "MICROINVERTER", tax_code: "TTR146714" },
  { name: "Enphase IQ8+ Microinverter", category: "Microinverters", unit_price: 189.0, unit: "each", tax_category: "MICROINVERTER", tax_code: "TTR146714" },
  { name: "Enphase IQ8A Microinverter", category: "Microinverters", unit_price: 221.78, unit: "each", tax_category: "MICROINVERTER", tax_code: "TTR146714" },
  { name: "Enphase M215 Microinverter", category: "Microinverters", unit_price: 181.0, unit: "each", tax_category: "MICROINVERTER", tax_code: "TTR146714" },
  { name: "Enphase IQ7A Microinverter", category: "Microinverters", unit_price: 192.0, unit: "each", tax_category: "MICROINVERTER", tax_code: "TTR146714" },
  { name: "Enphase IQ8X Microinverter", category: "Microinverters", unit_price: 228.5, unit: "each", tax_category: "MICROINVERTER", tax_code: "TTR146714" },
  { name: "Enphase IQ7+ Microinverter", category: "Microinverters", unit_price: 176.96, unit: "each", tax_category: "MICROINVERTER", tax_code: "TTR146714" },
  { name: "Enphase IQ8H-240 Microinverter", category: "Microinverters", unit_price: 245.88, unit: "each", tax_category: "MICROINVERTER", tax_code: "TTR146714" },
  { name: "8pcs SunPower 518636 End Clamp, Wedge, InvisiMount, Two Boxes", category: "Mounting / Racking", unit_price: 40.0, unit: "each", tax_category: "SOLAR_ACCESSORY", tax_code: "TTR146718" },
  { name: "Grounding Lug - Unirac Railing", category: "Mounting / Racking", unit_price: 10.0, unit: "each", tax_category: "SOLAR_ACCESSORY", tax_code: "TTR146718" },
  { name: "Unirac E-BOSS Conduit Mount 3.0 w/ Butyl Kit (1 pc)", category: "Mounting / Racking", unit_price: 7.28, unit: "each", tax_category: "SOLAR_ACCESSORY", tax_code: "TTR146718" },
  { name: "L-Foot Mounting Bracket (Universal)", category: "Mounting / Racking", unit_price: 8.5, unit: "each", tax_category: "SOLAR_ACCESSORY", tax_code: "TTR146718" },
  { name: "3/4 in. Aluminum Conduit Bender", category: "Rental Equipment", unit_price: 44.98, unit: "each", tax_category: "RENTAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "Pickup truck rental per day + gas", category: "Rental Equipment", unit_price: 107.5, unit: "day", tax_category: "RENTAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "Extension ladder - Rental cost per day", category: "Rental Equipment", unit_price: 72.5, unit: "day", tax_category: "RENTAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "Towable Boom Lift Rental - Texas", category: "Rental Equipment", unit_price: 600.0, unit: "day", tax_category: "RENTAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "Ladder rental", category: "Rental Equipment", unit_price: 150.0, unit: "day", tax_category: "RENTAL_EQUIPMENT", tax_code: "TTR152589" },
  { name: "thread sealant", category: "Roof Mounting & Sealing", unit_price: 6.48, unit: "each", tax_category: "SOLAR_ACCESSORY", tax_code: "TTR146718" },
  { name: "209XR Extreme Rubberized Wet Patch Black Roof Leak Repair Sealant Caulk", category: "Roof Mounting & Sealing", unit_price: 10.97, unit: "each", tax_category: "SOLAR_ACCESSORY", tax_code: "TTR146718" },
  { name: "IronRidge BX Mill Finish Bottom Clamp with Hardware", category: "Roof Mounting & Sealing", unit_price: 2.21, unit: "each", tax_category: "SOLAR_ACCESSORY", tax_code: "TTR146718" },
  { name: "IronRidge BX 35mm Mill Finish Top Clamp", category: "Roof Mounting & Sealing", unit_price: 1.55, unit: "each", tax_category: "SOLAR_ACCESSORY", tax_code: "TTR146718" },
  { name: "IronRidge Universal Mid Clamp, 30-45mm, w/ Bonding, Mill", category: "Roof Mounting & Sealing", unit_price: 4.89, unit: "each", tax_category: "SOLAR_ACCESSORY", tax_code: "TTR146718" },
  { name: "Scotch 3/4 in. x 25 ft. Extreme Weather Electrical Tape - Black", category: "Roof Mounting & Sealing", unit_price: 3.98, unit: "roll", tax_category: "SOLAR_ACCESSORY", tax_code: "TTR146718" },
  { name: "Frame Mount (40 mm) clip", category: "Roof Mounting & Sealing", unit_price: 4.1, unit: "each", tax_category: "SOLAR_ACCESSORY", tax_code: "TTR146718" },
  { name: "0.54 ft. Rooftop Support Block", category: "Roof Mounting & Sealing", unit_price: 12.93, unit: "each", tax_category: "SOLAR_ACCESSORY", tax_code: "TTR146718" },
  { name: "Duct Seal Putty", category: "Roof Mounting & Sealing", unit_price: 5.34, unit: "each", tax_category: "SOLAR_ACCESSORY", tax_code: "TTR146718" },
  { name: "Ironridge UFO-CL-01-B1, Module Clamps", category: "Roof Mounting & Sealing", unit_price: 3.78, unit: "each", tax_category: "SOLAR_ACCESSORY", tax_code: "TTR146718" },
  { name: "Dicor Self-Leveling Lap Sealant", category: "Roof Mounting & Sealing", unit_price: 9.5, unit: "each", tax_category: "SOLAR_ACCESSORY", tax_code: "TTR146718" },
  { name: "Butyl Tape Roll (1\"x50ft)", category: "Roof Mounting & Sealing", unit_price: 18.5, unit: "per roll", tax_category: "SOLAR_ACCESSORY", tax_code: "TTR146718" },
  { name: "Roof Flashing Boot (3/4\")", category: "Roof Mounting & Sealing", unit_price: 14.5, unit: "each", tax_category: "SOLAR_ACCESSORY", tax_code: "TTR146718" },
  { name: "Roof Flashing Boot (1/2\")", category: "Roof Mounting & Sealing", unit_price: 12.5, unit: "each", tax_category: "SOLAR_ACCESSORY", tax_code: "TTR146718" },
  { name: "Stainless Steel Lag Bolts (5/16\"x3\", 25pk)", category: "Roof Mounting & Sealing", unit_price: 15.5, unit: "per 25 pack", tax_category: "SOLAR_ACCESSORY", tax_code: "TTR146718" },
  { name: "Polyurethane Roof Sealant", category: "Roof Mounting & Sealing", unit_price: 8.75, unit: "each", tax_category: "SOLAR_ACCESSORY", tax_code: "TTR146718" },
  { name: "Through-Bolt Roof Mount Kit", category: "Roof Mounting & Sealing", unit_price: 42.0, unit: "per kit", tax_category: "SOLAR_ACCESSORY", tax_code: "TTR146718" },
  { name: "QuickBOLT Roof-Mounted Conduit Supports", category: "Roof Mounting & Sealing", unit_price: 79.25, unit: "each", tax_category: "SOLAR_ACCESSORY", tax_code: "TTR146718" },
  { name: "Tubes of Roof Mastic Caulk", category: "Roof Mounting & Sealing", unit_price: 7.5, unit: "each", tax_category: "SOLAR_ACCESSORY", tax_code: "TTR146718" },
  { name: "ATS Troubleshooting & Replacement", category: "Services", unit_price: 500.0, unit: "each", tax_category: "SERVICES", tax_code: "SS300220" },
  { name: "Utility Interconnection", category: "Services", unit_price: 500.0, unit: "each", tax_category: "SERVICES", tax_code: "SS300220" },
  { name: "AHJ Permitting", category: "Services", unit_price: 300.0, unit: "each", tax_category: "SERVICES", tax_code: "SS300220" },
  { name: "Load controller install/replace", category: "Services", unit_price: 0.0, unit: "each", tax_category: "SERVICES", tax_code: "SS300220" },
  { name: "Battery Installation", category: "Services", unit_price: 0.0, unit: "each", tax_category: "SERVICES", tax_code: "SS300220" },
  { name: "Array Mapping", category: "Services", unit_price: 0.0, unit: "each", tax_category: "SERVICES", tax_code: "SS300220" },
  { name: "Gateway install", category: "Services", unit_price: 0.0, unit: "each", tax_category: "SERVICES", tax_code: "SS300220" },
  { name: "Comprehensive Diagnostic (Troubleshooting)", category: "Services", unit_price: 450.0, unit: "each", tax_category: "SERVICES", tax_code: "SS300220" },
  { name: "Gateway Communication - Monitoring Troubleshoot or Replacement", category: "Services", unit_price: 450.0, unit: "each", tax_category: "SERVICES", tax_code: "SS300220" },
  { name: "Microinverter Replacement for RMA'ed 5 MI's and under", category: "Services", unit_price: 450.0, unit: "each", tax_category: "SERVICES", tax_code: "SS300220" },
  { name: "Alex Tech 25ft - 1/4 inch Split Wire Loom Tubing - Black", category: "Wiring & Cable Management", unit_price: 9.99, unit: "each", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "14 AWG White Stranded CU THHN Wire", category: "Wiring & Cable Management", unit_price: 1.2, unit: "ft", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "Wago 221-412 Wire Lever Nuts 2 Wire Conductor Compact Splicing Connectors", category: "Wiring & Cable Management", unit_price: 0.5, unit: "each", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "2 in. J Hook Cable Angle Bracket Support (50-Pack)", category: "Wiring & Cable Management", unit_price: 174.13, unit: "each", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "5-Terminal Ground Bar Kit - eaton", category: "Wiring & Cable Management", unit_price: 9.98, unit: "each", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "Butt Splice Crimp Connector 12-10 AWG Heat Shrink (5-Pack)", category: "Wiring & Cable Management", unit_price: 6.91, unit: "each", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "12-10 AWG Butt Splice Terminal with Heat Shrink Insulation (25-Pack)", category: "Wiring & Cable Management", unit_price: 11.88, unit: "each", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "14-4 AWG Copper Lay-In Lug Connector", category: "Wiring & Cable Management", unit_price: 12.58, unit: "each", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "Wing-Nut Wire Connector, 454 Blue, Bag of 25", category: "Wiring & Cable Management", unit_price: 13.98, unit: "each", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "50 ft. 8-Gauge Solid SD Bare Copper Grounding Wire", category: "Wiring & Cable Management", unit_price: 36.0, unit: "each", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "MC4 Cable Connectors with 6 each Male & Female - 12 pack 10AWG Solar Panel", category: "Wiring & Cable Management", unit_price: 35.98, unit: "each", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "4-14 AWG Bagged Insulated Tap Connector, Black", category: "Wiring & Cable Management", unit_price: 14.69, unit: "each", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "3/4 in. ACC Non-Metallic Strain Relief Cord Connector", category: "Wiring & Cable Management", unit_price: 3.29, unit: "each", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "Multi-Groove Fiberglass 100 ft. Fish Tape with Spiral Steel Leader", category: "Wiring & Cable Management", unit_price: 135.0, unit: "each", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "BR 15 Amp 120/240 Volts 2-Pole Circuit Breaker", category: "Wiring & Cable Management", unit_price: 21.32, unit: "each", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "10 White Stranded CU THHN Wire", category: "Wiring & Cable Management", unit_price: 1.05, unit: "ft", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "10 Black Stranded CU THHN Wire", category: "Wiring & Cable Management", unit_price: 1.05, unit: "ft", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "10 Green Stranded CU THHN Wire", category: "Wiring & Cable Management", unit_price: 1.05, unit: "ft", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "10 Red Stranded CU THHN Wire", category: "Wiring & Cable Management", unit_price: 0.8, unit: "ft", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "1 in. Non-Metallic Liquid-Tight Push-On Connector (each)", category: "Wiring & Cable Management", unit_price: 6.91, unit: "each", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "25 ft. #4-Gauge AWG Copper Wire", category: "Wiring & Cable Management", unit_price: 45.0, unit: "each", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "18 AWG, Black Wire, 100 ft.", category: "Wiring & Cable Management", unit_price: 0.29, unit: "ft", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "14 AWG Red Stranded Copper THHN Wire", category: "Wiring & Cable Management", unit_price: 1.2, unit: "ft", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "14 AWG Green Stranded Copper THHN Wire", category: "Wiring & Cable Management", unit_price: 1.2, unit: "ft", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "14 AWG Black Stranded Copper THHN Wire", category: "Wiring & Cable Management", unit_price: 1.2, unit: "ft", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "60 Amp 240-Volt 2-Pole Fused Outdoor General Duty Safety Switch", category: "Wiring & Cable Management", unit_price: 190.72, unit: "each", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "1/2\" Heat Shrink Tubing", category: "Wiring & Cable Management", unit_price: 2.99, unit: "each", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "3/8\" Heat Shrink Tubing", category: "Wiring & Cable Management", unit_price: 2.99, unit: "each", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "IQ Sealing Cap (Q-BA-CAP-10) Ea", category: "Wiring & Cable Management", unit_price: 3.35, unit: "each", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "3M Electrical Tape - 60 ft", category: "Wiring & Cable Management", unit_price: 2.98, unit: "each", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "1/4 in. Coaxial Cable Clamp RG-6 (20-Pack)", category: "Wiring & Cable Management", unit_price: 5.23, unit: "each", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "Water Proof/Weather Proof Wire Nuts - 15 pk", category: "Wiring & Cable Management", unit_price: 27.22, unit: "each", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "MC4 Connector (6-pack)", category: "Wiring & Cable Management", unit_price: 34.5, unit: "each", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "QD 12AWG Cable (Commercial) w/120 Male Connectors - 2.0m Max Module Pitch", category: "Wiring & Cable Management", unit_price: 203.5, unit: "each", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "3/4 in. Electrical Metallic Tube (EMT) Set-Screw Connectors (5-Pack)", category: "Wiring & Cable Management", unit_price: 5.45, unit: "each", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "1 in. Insulated Grounding Bushing", category: "Wiring & Cable Management", unit_price: 13.52, unit: "each", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "IronRidge XR-LUG-04-A1 Grounding Lug", category: "Wiring & Cable Management", unit_price: 7.03, unit: "each", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "6-Gauge Solid SD Bare Copper Grounding Wire", category: "Wiring & Cable Management", unit_price: 1.63, unit: "ft", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "Polaris 4-14 AWG Bagged Insulated Tap Connector, Black", category: "Wiring & Cable Management", unit_price: 13.97, unit: "each", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "Solar Panel Clips (Pack of 50)", category: "Wiring & Cable Management", unit_price: 10.0, unit: "each", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "MC4 Connector Pair", category: "Wiring & Cable Management", unit_price: 3.25, unit: "per pair", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "10 AWG PV Wire (Black)", category: "Wiring & Cable Management", unit_price: 0.68, unit: "per foot", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "10 AWG PV Wire (Green) - per foot", category: "Wiring & Cable Management", unit_price: 0.68, unit: "ft", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "10 AWG PV Wire (White) - per foot", category: "Wiring & Cable Management", unit_price: 0.98, unit: "ft", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "10 AWG PV Wire (Red)", category: "Wiring & Cable Management", unit_price: 0.68, unit: "per foot", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "Wire Nuts - Blue (100pk)", category: "Wiring & Cable Management", unit_price: 6.5, unit: "per 100 pack", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "Wire Nuts - Red (100pk)", category: "Wiring & Cable Management", unit_price: 7.25, unit: "per 100 pack", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "Wire Nuts - Yellow (100pk)", category: "Wiring & Cable Management", unit_price: 8.5, unit: "per 100 pack", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "8\" Black UV-Rated Zip Ties (100pk)", category: "Wiring & Cable Management", unit_price: 6.75, unit: "per 100 pack", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "14\" Black UV-Rated Zip Ties (100pk)", category: "Wiring & Cable Management", unit_price: 12.5, unit: "per 100 pack", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "11 inch Black UV-Rated Zip Ties (100pk)", category: "Wiring & Cable Management", unit_price: 9.48, unit: "per 100 pack", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "MC4 Y-Branch Connector Pair", category: "Wiring & Cable Management", unit_price: 8.5, unit: "per pair", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "Split-Bolt Connector (3-pack)", category: "Wiring & Cable Management", unit_price: 4.75, unit: "per 3-pack", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "#12 Black Stranded Copper THHN Wire", category: "Wiring & Cable Management", unit_price: 0.97, unit: "ft", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "#12 Green Stranded CU THHN Wire", category: "Wiring & Cable Management", unit_price: 0.97, unit: "ft", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "#12 White Stranded CU THHN Wire - 1 FT", category: "Wiring & Cable Management", unit_price: 0.96, unit: "each", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "#8 THHN Stranded Copper", category: "Wiring & Cable Management", unit_price: 1.15, unit: "per foot", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "#10 THHN Stranded Copper", category: "Wiring & Cable Management", unit_price: 0.57, unit: "per foot", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "#6 THHN Stranded Copper", category: "Wiring & Cable Management", unit_price: 1.85, unit: "per foot", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "Homeline 60 Amp 2-Pole Circuit Breaker (HOM260CP)", category: "Wiring & Cable Management", unit_price: 17.47, unit: "each", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" },
  { name: "POLARIS Multitap Connector: 2 Port, Double-Sided Entry, 14 AWG - 4 AWG Wire Size, Black", category: "Wiring & Cable Management", unit_price: 24.39, unit: "each", tax_category: "SOLAR_CABLES_CONNECTORS", tax_code: "TTR146716" }
];

